# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cartesian_control/CartesianCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class CartesianCommand(genpy.Message):
  _md5sum = "e5ffe3cb2eac6f1acc27e5635f953be7"
  _type = "cartesian_control/CartesianCommand"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Transform x_target
bool secondary_objective
float32 q0_target
================================================================================
MSG: geometry_msgs/Transform
# This represents the transform between two coordinate frames in free space.

Vector3 translation
Quaternion rotation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['x_target','secondary_objective','q0_target']
  _slot_types = ['geometry_msgs/Transform','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_target,secondary_objective,q0_target

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CartesianCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x_target is None:
        self.x_target = geometry_msgs.msg.Transform()
      if self.secondary_objective is None:
        self.secondary_objective = False
      if self.q0_target is None:
        self.q0_target = 0.
    else:
      self.x_target = geometry_msgs.msg.Transform()
      self.secondary_objective = False
      self.q0_target = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7dBf().pack(_x.x_target.translation.x, _x.x_target.translation.y, _x.x_target.translation.z, _x.x_target.rotation.x, _x.x_target.rotation.y, _x.x_target.rotation.z, _x.x_target.rotation.w, _x.secondary_objective, _x.q0_target))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x_target is None:
        self.x_target = geometry_msgs.msg.Transform()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.x_target.translation.x, _x.x_target.translation.y, _x.x_target.translation.z, _x.x_target.rotation.x, _x.x_target.rotation.y, _x.x_target.rotation.z, _x.x_target.rotation.w, _x.secondary_objective, _x.q0_target,) = _get_struct_7dBf().unpack(str[start:end])
      self.secondary_objective = bool(self.secondary_objective)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7dBf().pack(_x.x_target.translation.x, _x.x_target.translation.y, _x.x_target.translation.z, _x.x_target.rotation.x, _x.x_target.rotation.y, _x.x_target.rotation.z, _x.x_target.rotation.w, _x.secondary_objective, _x.q0_target))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x_target is None:
        self.x_target = geometry_msgs.msg.Transform()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.x_target.translation.x, _x.x_target.translation.y, _x.x_target.translation.z, _x.x_target.rotation.x, _x.x_target.rotation.y, _x.x_target.rotation.z, _x.x_target.rotation.w, _x.secondary_objective, _x.q0_target,) = _get_struct_7dBf().unpack(str[start:end])
      self.secondary_objective = bool(self.secondary_objective)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dBf = None
def _get_struct_7dBf():
    global _struct_7dBf
    if _struct_7dBf is None:
        _struct_7dBf = struct.Struct("<7dBf")
    return _struct_7dBf
