// Generated by gencpp from file assignment0/TwoInt.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT0_MESSAGE_TWOINT_H
#define ASSIGNMENT0_MESSAGE_TWOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment0
{
template <class ContainerAllocator>
struct TwoInt_
{
  typedef TwoInt_<ContainerAllocator> Type;

  TwoInt_()
    : num1(0)
    , num2(0)  {
    }
  TwoInt_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int8_t _num1_type;
  _num1_type num1;

   typedef int8_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::assignment0::TwoInt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment0::TwoInt_<ContainerAllocator> const> ConstPtr;

}; // struct TwoInt_

typedef ::assignment0::TwoInt_<std::allocator<void> > TwoInt;

typedef boost::shared_ptr< ::assignment0::TwoInt > TwoIntPtr;
typedef boost::shared_ptr< ::assignment0::TwoInt const> TwoIntConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment0::TwoInt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment0::TwoInt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment0::TwoInt_<ContainerAllocator1> & lhs, const ::assignment0::TwoInt_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment0::TwoInt_<ContainerAllocator1> & lhs, const ::assignment0::TwoInt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment0

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment0::TwoInt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment0::TwoInt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment0::TwoInt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment0::TwoInt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment0::TwoInt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment0::TwoInt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment0::TwoInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57106ecc5f261c3b4e1105c1171fe312";
  }

  static const char* value(const ::assignment0::TwoInt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57106ecc5f261c3bULL;
  static const uint64_t static_value2 = 0x4e1105c1171fe312ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment0::TwoInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment0/TwoInt";
  }

  static const char* value(const ::assignment0::TwoInt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment0::TwoInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 num1\n"
"int8 num2\n"
;
  }

  static const char* value(const ::assignment0::TwoInt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment0::TwoInt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwoInt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment0::TwoInt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment0::TwoInt_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT0_MESSAGE_TWOINT_H
